name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      dynamodb-local:
        image: "amazon/dynamodb-local:latest"
        # options: >-
        #   --entrypoint "java -jar DynamoDBLocal.jar -sharedDb"
        ports:
          - 8000:8000

    steps:
      - uses: actions/checkout@v2

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: test
      #     aws-secret-access-key: test
      #     aws-region: eu-west-1

      - name: Setup DynamoDB
        run: |
          AWS_PAGER="" aws dynamodb create-table --cli-input-json "file://./examples/create-table.json" --endpoint-url "http://dynamodb-local:8000"
          aws dynamodb put-item  --cli-input-json "file://./examples/put-item.json" --endpoint-url "http://dynamodb-local:8000"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
