name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      dynamodb-local:
        image: "amazon/dynamodb-local:latest"
        # options: >-
        #   --entrypoint "java -jar DynamoDBLocal.jar -sharedDb"
        ports:
          - 8000:8000

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
